"""Formats flagged episodes into the report output format."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape

from .fetcher import Episode
from .matcher import FlagResult


@dataclass
class FlaggedEpisode:
    episode: Episode
    result: FlagResult


def _fmt_date(dt: datetime | None) -> str:
    return dt.strftime("%Y-%m-%d") if dt else "Unknown"


def to_markdown(flagged: list[FlaggedEpisode]) -> str:
    if not flagged:
        return "No episodes matched the Middle Eastern / Israeli cuisine criteria in this scan.\n"

    lines = []
    for f in sorted(flagged, key=lambda x: x.episode.published or datetime.min.replace(tzinfo=timezone.utc), reverse=True):
        ep, res = f.episode, f.result
        keywords = ", ".join(sorted({m.text for m in res.matched_keywords}))
        lines.append(f"## {ep.title}")
        lines.append(f"- **Podcast:** {ep.podcast_name}")
        lines.append(f"- **Release date:** {_fmt_date(ep.published)}")
        lines.append(f"- **Matched keywords:** {keywords}")
        lines.append(f"- **Reason for flag:** {res.reason}")
        lines.append(f"- **Confidence:** {res.confidence}")
        if ep.link:
            lines.append(f"- **Link:** {ep.link}")
        lines.append("")
    return "\n".join(lines)


_CONFIDENCE_CLASS = {"High": "high", "Medium": "medium", "Low": "low"}

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Eli Podcast Monitor</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    max-width: 780px;
    margin: 0 auto;
    padding: 2.5rem 1.25rem 4rem;
    line-height: 1.5;
    color: #1c1c1e;
    background: #fafafa;
  }}
  header {{ margin-bottom: 2rem; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 0.25rem; }}
  .subtitle {{ color: #666; font-size: 0.95rem; }}
  .card {{
    background: #fff;
    border: 1px solid #e3e3e3;
    border-radius: 10px;
    padding: 1.25rem 1.5rem;
    margin-bottom: 1.1rem;
  }}
  .card h2 {{ font-size: 1.15rem; margin: 0 0 0.5rem; }}
  .meta {{ font-size: 0.9rem; color: #444; margin: 0.15rem 0; }}
  .meta strong {{ color: #111; }}
  .badge {{
    display: inline-block;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.15rem 0.55rem;
    border-radius: 999px;
    margin-left: 0.4rem;
  }}
  .badge.high {{ background: #dff5e1; color: #1a7431; }}
  .badge.medium {{ background: #fff3d6; color: #8a5a00; }}
  .badge.low {{ background: #eee; color: #555; }}
  .keywords span {{
    display: inline-block;
    background: #f1eefc;
    color: #4b3aa4;
    font-size: 0.8rem;
    padding: 0.1rem 0.5rem;
    border-radius: 6px;
    margin: 0.15rem 0.25rem 0 0;
  }}
  a {{ color: #4b3aa4; }}
  footer {{ margin-top: 2.5rem; font-size: 0.8rem; color: #888; }}
  .empty {{ color: #666; font-style: italic; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #121212; color: #eaeaea; }}
    .card {{ background: #1c1c1e; border-color: #2e2e2e; }}
    .card h2 {{ color: #fff; }}
    .meta {{ color: #bbb; }}
    .meta strong {{ color: #f2f2f2; }}
    .keywords span {{ background: #2a2440; color: #c9bdf5; }}
    footer {{ color: #888; }}
  }}
</style>
</head>
<body>
<header>
  <h1>Eli Podcast Monitor</h1>
  <p class="subtitle">Middle Eastern / Israeli cuisine &amp; behind-the-scenes chef content, flagged from monitored podcasts.</p>
  <p class="subtitle">Last updated: {generated_at} &middot; {count} flagged episode(s)</p>
</header>
{body}
<footer>
  {note}
  Generated by the <a href="https://github.com/elipstein/Eli_Podcast_Monitor">Eli_Podcast_Monitor</a> scan.
  Source lists and matching rules live in <code>podcast_monitor/keywords.py</code>.
</footer>
</body>
</html>
"""

_CARD_TEMPLATE = """<div class="card">
  <h2 dir="auto">{title}</h2>
  <p class="meta" dir="auto"><strong>Podcast:</strong> {podcast}</p>
  <p class="meta"><strong>Release date:</strong> {date}</p>
  <p class="meta"><strong>Confidence:</strong> <span class="badge {conf_class}">{confidence}</span></p>
  <p class="meta" dir="auto"><strong>Reason:</strong> {reason}</p>
  <p class="meta keywords" dir="auto"><strong>Matched keywords:</strong><br>{keywords}</p>
  {link}
</div>
"""


def to_html(flagged: list[FlaggedEpisode], generated_at: datetime | None = None, note: str = "") -> str:
    generated_at = generated_at or datetime.now(timezone.utc)
    generated_str = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    note_html = f"<p>{escape(note)}</p>" if note else ""

    if not flagged:
        body = '<p class="empty">No episodes matched the criteria in the most recent scan.</p>'
        return _HTML_TEMPLATE.format(generated_at=generated_str, body=body, note=note_html, count=0)

    cards = []
    for f in sorted(flagged, key=lambda x: x.episode.published or datetime.min.replace(tzinfo=timezone.utc), reverse=True):
        ep, res = f.episode, f.result
        keywords_html = "".join(f"<span>{escape(k)}</span>" for k in sorted({m.text for m in res.matched_keywords}))
        link_html = f'<p class="meta"><a href="{escape(ep.link)}">Listen / show notes &rarr;</a></p>' if ep.link else ""
        cards.append(
            _CARD_TEMPLATE.format(
                title=escape(ep.title),
                podcast=escape(ep.podcast_name),
                date=_fmt_date(ep.published),
                conf_class=_CONFIDENCE_CLASS.get(res.confidence, "low"),
                confidence=escape(res.confidence),
                reason=escape(res.reason),
                keywords=keywords_html,
                link=link_html,
            )
        )
    return _HTML_TEMPLATE.format(generated_at=generated_str, body="\n".join(cards), note=note_html, count=len(flagged))


def to_dicts(flagged: list[FlaggedEpisode]) -> list[dict]:
    out = []
    for f in flagged:
        ep, res = f.episode, f.result
        out.append(
            {
                "podcast_name": ep.podcast_name,
                "episode_title": ep.title,
                "release_date": _fmt_date(ep.published),
                "matched_keywords": sorted({m.text for m in res.matched_keywords}),
                "reason_for_flag": res.reason,
                "confidence": res.confidence,
                "link": ep.link,
            }
        )
    return out
